buildscript {
	ext {
		grailsVersion = project.grailsVersion
	}
	repositories {
		mavenLocal()
		maven {
            url = "https://repo.grails.org/grails/core"
        }
	}
	dependencies {
		classpath "org.apache.grails:grails-gradle-plugins:${grailsVersion}"
	}
}

plugins {
    id 'eclipse'
    id 'idea'
	id 'maven-publish'
	id "com.github.ben-manes.versions" version "${benManesVersion}"
}

version = "5.0.0-SNAPSHOT"
group = "org.grails.plugins"

apply plugin: 'org.apache.grails.gradle.grails-plugin'

ext {
	grailsVersion = project.grailsVersion
}

repositories {
	mavenLocal()
	mavenCentral()
	maven {
        url = "https://repo.grails.org/grails/core"
    }
}

dependencies {
    implementation "org.springframework.boot:spring-boot-starter-logging"
	implementation "org.springframework.boot:spring-boot-autoconfigure"
	implementation "org.apache.grails:grails-core"

	runtimeOnly "org.apache.grails:grails-web-boot"
	runtimeOnly "org.apache.grails:grails-dependencies-starter-web"
	runtimeOnly "javax.servlet:javax.servlet-api:${servletApiVersion}"

    console "org.apache.grails:grails-console"

    profile "org.apache.grails.profiles:plugin"

	implementation "org.apache.commons:commons-lang3:${commonsLang3Version}"
	implementation "org.apache.cxf:cxf-core:${cxfVersion}"
	implementation "org.apache.cxf:cxf-rt-frontend-jaxws:${cxfVersion}"
	implementation "org.apache.cxf:cxf-rt-frontend-jaxrs:${cxfVersion}"
	implementation "org.apache.cxf:cxf-rt-transports-http:${cxfVersion}"

	testImplementation "org.spockframework:spock-core"
}

tasks.withType(Test) {
	useJUnitPlatform()
}

jar {
	exclude 'org/grails/cxf/test/**'
}

publishing {
	publications {
		library(MavenPublication) {
			from components.java
		}
	}
}
