[[annotationReference]]
=== Exposing Classes Via Annotation

When using the annotation, the property values will only be used if the corresponding annotation value is not
provided or is set to the default value. The following are available to configure via the annotation:

[source,groovy]
----
/**
 * Annotation to be used to expose a Service or Endpoint class as a CXF Service via Grails.
 */
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.TYPE)
@interface GrailsCxfEndpoint {
    String address() default ''
    String name() default ''
    String port() default ''
    EndpointType expose() default EndpointType.JAX_WS
    boolean soap12() default false
    String wsdl() default ''
    //Interceptors
    String[] inInterceptors() default []
    String[] outInterceptors() default []
    String[] inFaultInterceptors() default []
    String[] outFaultInterceptors() default []
    GrailsCxfEndpointProperty[] properties() default []
}

@Target(ElementType.METHOD)
@interface GrailsCxfEndpointProperty {
    public String name() default ''
    public String value() default ''
}
----

==== address

The address property is used to adjust the endpoint address that the service will be deployed to. By default, if
not provided or the value is empty (`""`), this will be the name of the Service or Endpoint with the first letter
lowercase and the word `Endpoint` or `Service` removed from the end of the name. The default behavior would deploy
the `BoatService` as `/services/boat`.

If you wish to override this and provide your own service name or address (for versioning support for example) you
may set this value.

[source,groovy]
----
@GrailsCxfEndpoint(address='/v2/custom/path')
class CarService {
    ...
}
----

The above would be deployed to `/services/v2/custom/path`.

==== expose

The `expose` property will tell the plugin how you wish to expose. The default is `EndpointType.JAX_WS` which is the
same as the following:

[source,groovy]
----
@GrailsCxfEndpoint(expose=EndpointType.JAX_WS)
class CarService {
    ...
}
----

Simple and JaxRS types are currently not supported. *TODO*

==== name

The `name` property will tell the plugin how you wish to name the service. This will change the WSDL name property
from the default for the example below from `CarService` to simply `Car`, like this:
`<wsdl:definitions name="Car" targetNamespace="http://demo.gpc.com">`

[source,groovy]
----
@GrailsCxfEndpoint(name='Car')
class CarService {
    ...
}
----

==== port

The `port` property will tell the plugin how you wish to name the service port binding. This will change the WSDL
name property of the port from the default for the example below from `CarServicePort` to simply `CarPort`, like
this: `<wsdl:port binding="tns:CarServiceSoapBinding" name="CarPort">`

[source,groovy]
----
@GrailsCxfEndpoint(port='CarPort')
class CarService {
    ...
}
----

==== soap12

To tell a service to default to SOAP 1.2 instead of 1.1 simply set this to `true`. The default value is `false`
which will use SOAP 1.1.

[source,groovy]
----
@GrailsCxfEndpoint(soap12=true)
class CarService {
    ...
}
----

==== wsdl

To expose as a WSDL-first JAX-WS endpoint (see the
https://cxf.apache.org/docs/jax-ws-configuration.html[CXF JAX-WS configuration docs]) add the `wsdl` property and
classpath to the WSDL, as well as setting the endpoint type to `EndpointType.JAX_WS_WSDL`.

[source,groovy]
----
@WebService(name = 'CustomerServiceWsdlEndpoint',
targetNamespace = 'http://test.cxf.grails.org/',
serviceName = 'CustomerServiceWsdlEndpoint',
portName = 'CustomerServiceWsdlPort')
@GrailsCxfEndpoint(wsdl = 'org/grails/cxf/test/soap/CustomerService.wsdl', expose = EndpointType.JAX_WS_WSDL)
class AnnotatedCustomerServiceWsdlEndpoint {

    CustomerServiceEndpoint customerServiceEndpoint

    List<Customer> getCustomersByName(final String name) {
        customerServiceEndpoint.getCustomersByName(name)
    }
}
----

[[interceptorProperties]]
==== inInterceptors, outInterceptors, inFaultInterceptors, outFaultInterceptors

These are lists of bean names (`List<String>`) to inject into the CXF service endpoint. You will need to define
your interceptor beans via the normal Spring DSL (in `resources.groovy` for example).

This is helpful when the default CXF annotation of
`@org.apache.cxf.interceptor.InInterceptors (interceptors = {"com.example.Test1Interceptor" })` does not satisfy
your needs.

When choosing between this property and the CXF-provided one, if you require value injection, the CXF-provided
annotation will most likely *NOT* meet your needs and you should use this property instead.

NOTE: Make sure to set any beans you wish injected into your interceptors to `bean.autowire = 'byName'` or use the
`@Autowired` annotation.

See <<interceptors>> for a full example.

==== Conclusion

Using the annotation will help reduce the clutter of having many static properties in your class to configure CXF.
